from typing import Callable, Protocol
from .step import Step, Address


class MPT(Protocol):
    def get_node(self, key: bytes) -> bytes: ...
    def put_node(self, key: bytes, value: bytes) -> None: ...


class StepsTrace(Protocol):
    def world_accounts(self) -> MPT: ...
    def account_storage(self, address: Address) -> MPT: ...

    def last(self) -> Step: ...
    def by_index(self) -> Step: ...
    def length(self) -> int: ...


Processor = Callable[[StepsTrace], Step]

